Okari branch: Hello Microverse Project
2004-okari/HELLO_MICROVERSE pull request #1
Opened 2023-05-31 14:01 UTC by 2004-okari

Request to merge to the main branch.

2023-05-31 16:17 UTC, shahadat3669 requested changes
Hi @2004-okari , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
✅ Correct use of GitHub flow

## Required Changes ♻️
-  Please ensure that you use meaningful branch names for your branches, as the current branch name does not appear to reflect the implemented project features. It is important to choose descriptive branch names that provide a clear understanding of the changes or additions made in the branch. e.g. 'created_sidebar' or 'added_comments_section'
![image](https://github.com/2004-okari/HELLO_MICROVERSE/assets/55840999/ddfb21c9-af10-4a21-8dd1-8d8a96caf983)

-  Kindly write a meaningful PR title for your pull request, because I can see your PR title is long and not seems to be meaningful as per the project feature implemented.

| Your        | Professional |
|---------------------|-----------------------|
|  ![image](https://github.com/2004-okari/HELLO_MICROVERSE/assets/55840999/44fba67e-6397-486e-8087-f45ea187497e)   |    ![image](https://github.com/2004-okari/HELLO_MICROVERSE/assets/55840999/59a63a5d-1824-4ed3-a12c-63214fc51980)   |

- Please try to write a descriptive PR as I can see that your PR description is one line which is not professional at all, having a descriptive PR will help any person to understand your project feature implementation detail.

| Your | Professional |
| ------------- | --------------------- |
| ![image](https://github.com/2004-okari/HELLO_MICROVERSE/assets/55840999/74dbd8db-a3ff-4b6f-a8c5-14046243c25b) | ![image](https://github.com/Isaac-ej/Hello_Microverse/assets/55840999/36faff6a-bc00-463b-bca6-3b4931249584) |
- Ensure that you properly set up your linter by following the guidelines provided in the [Linter documentation](https://github.com/microverseinc/linters-config/tree/master/html-css). Currently, your linters.yml file is located inside .github/linters.yml, whereas it should be inside .github/workflow/linters.yml for it to function correctly. Please make the necessary adjustments to the file location.
- By setting up the linter properly and including a complete configuration, you can enhance the overall quality and maintainability of your codebase. Keep up the good work and follow the linter documentation closely!

_Check the comments under the review._

## Optional suggestions
- Additionally, consider providing a comprehensive linter configuration for your local machine. This will help ensure consistent code quality and adherence to coding standards during development. 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Setup linter for local mechine
- Remove unnecessary placeholder text

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-31 16:17 UTC, shahadat3669 commented on README.md
> +-->
Great job on the README file! However, it's important to note that the README template explicitly mentions the need to remove comments and instructions once the file is complete. 

I kindly request you to ensure their removal, as it will greatly enhance the overall clarity and usability of the document. Keep up the good work!

2023-05-31 16:17 UTC, shahadat3669 commented on README.md
> +  <img src="murple_logo.png" alt="logo" width="140"  height="auto" />
Wow, :+1: I appreciate your intention to use a custom logo for your project! However, I couldn't find any file named "murple_logo.png" in your repository, resulting in a broken link. To resolve this issue, you have two options: either remove the logo section altogether or add a logo file named "murple_logo.png" to your repository. Taking either action will ensure a seamless experience for users visiting your project.

2023-05-31 16:17 UTC, shahadat3669 commented on README.md
> +    -linters
While reviewing your document, I noticed that the Table of Contents includes not only headings but also additional details. To maintain consistency and clarity, it is recommended to include only the headings in the Table of Contents, while saving the details for the respective sections. This adjustment will enhance the overall organization and navigation of your document.
Please remove them from the table of contents section.

| Yours | Professional | 
| ------------- | ------------- |
| ![image](https://github.com/2004-okari/HELLO_MICROVERSE/assets/55840999/d31f8d15-92fa-46b6-8148-86f4e9b15776) | ![image](https://github.com/2004-okari/HELLO_MICROVERSE/assets/55840999/d60aca81-5403-43db-b8f6-91b01e305902) |

2023-05-31 16:17 UTC, shahadat3669 commented on README.md
> +
Your project has a great project description:+1:, highlighting its key features and purpose. However, it's essential to include a descriptive section in your README file as well. By adding a project description in the README, you will provide potential users and contributors with a clear understanding of your project right from the start. 

Please ensure to include this vital information in your README file to enhance its comprehensiveness. Also, kindly remove the '[ ]' symbols in the title. Keep up the excellent work!

| Your | Professional |
|---------------------|-----------------------|
| ![image](https://github.com/2004-okari/HELLO_MICROVERSE/assets/55840999/c3a6420d-e9ff-4478-bd67-3b5def321691)   | ![image](https://github.com/2004-okari/HELLO_MICROVERSE/assets/55840999/9b425824-02e1-4c65-b6cd-6e83b0ec70db) |

2023-05-31 16:17 UTC, shahadat3669 commented on README.md
> +</details>
Greate You added the "built-with" section. However, I recommend removing the placeholder text from the template and adding the necessary details. Additionally, please update the client summary by including technologies like HTML and CSS since you are utilizing them. 

As this project does not involve a server or database, it's advisable to remove any mentions or references to them, as they are not relevant in this context. By focusing on the specific technologies and components used, your README will remain concise and aligned with the project's scope. 

Excellent work so far, and keep up the good work!😄
| Your  | Professional |
|---------------------|-----------------------|
| ![image](https://github.com/2004-okari/HELLO_MICROVERSE/assets/55840999/d6afba07-9588-4271-be4b-c33b2e78662e)   | ![image](https://github.com/2004-okari/HELLO_MICROVERSE/assets/55840999/bfc33824-b97e-4f5e-951f-439df8ae0671) |

2023-05-31 16:17 UTC, shahadat3669 commented on README.md
> +
Good job on adding the key features section to your README! However, it seems that you have overlooked removing the placeholder text from the README template. Kindly remove the placeholder text and replace it with a meaningful and comprehensive list of the key features of your project. This will provide readers with a clear understanding of what your project has to offer. Keep up the great work and ensure that the README accurately reflects the full set of key features in your project!

| Your | Professional |
|---------------------|-----------------------|
|  ![image](https://github.com/2004-okari/HELLO_MICROVERSE/assets/55840999/32d109db-cb08-41a7-9623-54fc857e1a6e)|  ![image](https://github.com/2004-okari/HELLO_MICROVERSE/assets/55840999/0ecf523b-1b3c-452a-8441-b97af4a52c81) |

2023-05-31 16:17 UTC, shahadat3669 commented on README.md
> +
Great work on the Readme file! However, if you have decided not to deploy the application now, remove this section, or you can deploy it and add the deployed link in this section. If you're unsure about how to deploy the application, don't worry, you will learn it in a future project. In the meantime, feel free to delete this section and ensure that the 'live demo' is also removed from the **Table of Contents**.

Please remove the live demo section if the application won't be deployed.
![image](https://github.com/wacoo/Hello-Microverse/assets/55840999/84580445-f6ed-431a-9f17-775311b7d719)
![image](https://github.com/2004-okari/HELLO_MICROVERSE/assets/55840999/f7f5f6f7-1e45-471a-8c57-0f745201de36)

2023-05-31 16:17 UTC, shahadat3669 commented on README.md
> +
Great job on including an author section and including your name in the README! However, it's essential to also include links to your GitHub, LinkedIn, and Twitter profiles in order to provide readers with an opportunity to connect with you and explore your online presence. Adding these social media links will enhance the accessibility and engagement potential of your project. 
Please:pray: don't forget to include the relevant links to your GitHub, LinkedIn, and Twitter profiles in the author section of your README. Also as earlier said, please remove placeholder text. Keep up the excellent work!

| Your        | Professional |
|---------------------|-----------------------|
|   ![image](https://github.com/2004-okari/HELLO_MICROVERSE/assets/55840999/2dfee0c3-f4d4-45b2-a151-7e289016cd75)  |  ![image](https://github.com/2004-okari/HELLO_MICROVERSE/assets/55840999/2de40e9e-f037-4feb-bc1f-5cf1e3f7105c) |

2023-05-31 16:17 UTC, shahadat3669 commented on README.md
> +_NOTE: we recommend using the [MIT license](https://choosealicense.com/licenses/mit/) - you can set it up quickly by [using templates available on GitHub](https://docs.github.com/en/communities/setti
Please remove the placeholder text from your README file as it currently detracts from the overall quality of the document. By eliminating the placeholder text and replacing it with relevant and meaningful content, you will significantly improve the readability and professionalism of your README file. Take the opportunity to provide clear and concise information that accurately represents your project. Keep up the good work and ensure that the README is free from any unnecessary placeholders.

![image](https://github.com/2004-okari/HELLO_MICROVERSE/assets/55840999/7dd82394-3863-4ea9-be3f-3403089f33f1)

2023-05-31 16:17 UTC, shahadat3669 commented on README.md
> +This project is [MIT](./LICENSE) licensed.
Wonderful job on including the license section in your README! I noticed that you have a license file named "MIT.md" in your repository. However, in the license section of your README, there is a broken link to "LICENSE." To ensure a seamless user experience, please update the link to point directly to the "MIT.md" license file in your repository. This will provide clarity and make it easier for users to access the license information. 

Keep up the great work, and don't forget to fix the broken link! :grinning:

![image](https://github.com/2004-okari/HELLO_MICROVERSE/assets/55840999/c5e055e7-9d70-4269-ad43-e5be5170c4c4)

2023-05-31 16:17 UTC, shahadat3669 commented on README.md
> +- [❓ FAQ (OPTIONAL)](#faq)
Great work on the Readme file! 😀 However, if you have decided not to add any FAQ questions at the moment, it would be best to remove the FAQ section link from the Table of Contents Alternatively, if you have some frequently asked questions in mind, you can add them to provide additional information to users.

By keeping the Readme focused and concise, users will be able to easily navigate and find the information they need. Keep up the good work.

Example FAQ:👇

Q1: Can I use your Repo for personal use?
Ans: Yes, you can. Please check out the license section

2023-05-31 16:17 UTC, shahadat3669 commented on README.md
> +> Give credit to everyone who inspired your codebase.
Good job on adding the acknowledgments section to your README! However, it seems that you have overlooked removing the placeholder text from the README template. Kindly remove the placeholder text.:pray:

2023-05-31 16:17 UTC, shahadat3669 commented on README.md
> +- [🔭 Future Features](#future-features)
Well done on adding the 'Future Features' section heading!👍 However, it would be god to add "future features" and include 1-3 potential features in this section. Remember in this section, you should outline your plans for the future development of the project. Include details about the features, functionalities, or improvements you intend to add. It should demonstrate your vision and give readers an idea of what to expect. Keep up the good work!

Please include 1-3 potential fractures in this section.
| Your        | Professional |
|---------------------|-----------------------|
| ![image](https://github.com/2004-okari/HELLO_MICROVERSE/assets/55840999/464d5dd0-1ac1-4aee-8967-4b3b06abb736)  | ![image](https://github.com/2004-okari/HELLO_MICROVERSE/assets/55840999/6c06d9c5-1153-4928-bfd9-d55057f77c97) |

Example feature:

- I will deploy this project

2023-05-31 16:17 UTC, shahadat3669 commented on MIT.md
Good job on including the license file in your project! However, the contents of the license file you added don't match the template provided. To ensure you have a proper license file, you can refer to the [readme template repository](https://github.com/microverseinc/readme-template), where you'll find a file named 'MIT' that corresponds to the MIT license. Please add or copy the text from that file to your repository, making sure to delete any placeholders. Then, update the license section in your README with a link to the license file. This will ensure that users have access to the accurate license terms and understand the permissions and restrictions associated with your project. Keep up the great work! 👍

| Your        | Professional |
|---------------------|-----------------------|
| ![image](https://github.com/2004-okari/HELLO_MICROVERSE/assets/55840999/3f986465-328c-47ab-a0b3-db358188f1a6)  |  ![image](https://github.com/2004-okari/HELLO_MICROVERSE/assets/55840999/8b81323f-7659-4f4f-896e-a475bb80faf5) |

2023-06-01 07:48 UTC, closed without merging

2023-06-01 08:58 UTC, 2004-okari commented
Hello, do I submit the same link as the previous pull request?